import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import {
  htmlFromFile,
  textFromFile,
  attachmentFromFile,
  attachmentFromBuffer,
} from "../dist/node.js";

async function withTempDir(run) {
  const dir = await mkdtemp(join(tmpdir(), "sendstack-node-"));
  try {
    return await run(dir);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

test("htmlFromFile reads a UTF-8 file into a string", async () => {
  await withTempDir(async (dir) => {
    const path = join(dir, "welcome.html");
    await writeFile(path, "<p>Hëllo</p>", "utf8");

    assert.equal(await htmlFromFile(path), "<p>Hëllo</p>");
  });
});

test("textFromFile reads a UTF-8 file into a string", async () => {
  await withTempDir(async (dir) => {
    const path = join(dir, "welcome.txt");
    await writeFile(path, "Hëllo", "utf8");

    assert.equal(await textFromFile(path), "Hëllo");
  });
});

test("attachmentFromFile base64-encodes and defaults filename to the basename", async () => {
  await withTempDir(async (dir) => {
    const path = join(dir, "invoice.pdf");
    await writeFile(path, Buffer.from("%PDF-1.4 fake"));

    const attachment = await attachmentFromFile(path);

    assert.deepEqual(attachment, {
      filename: "invoice.pdf",
      contentBase64: Buffer.from("%PDF-1.4 fake").toString("base64"),
    });
  });
});

test("attachmentFromFile honors overrides and metadata options", async () => {
  await withTempDir(async (dir) => {
    const path = join(dir, "logo.png");
    await writeFile(path, Buffer.from([0x89, 0x50, 0x4e, 0x47]));

    const attachment = await attachmentFromFile(path, {
      filename: "brand-logo.png",
      contentType: "image/png",
      inline: true,
      contentId: "logo",
    });

    assert.deepEqual(attachment, {
      filename: "brand-logo.png",
      contentBase64: Buffer.from([0x89, 0x50, 0x4e, 0x47]).toString("base64"),
      contentType: "image/png",
      inline: true,
      contentId: "logo",
    });
  });
});

test("attachmentFromFile accepts a file URL and derives the basename from it", async () => {
  await withTempDir(async (dir) => {
    const path = join(dir, "report.csv");
    await writeFile(path, "a,b\n1,2\n");

    const attachment = await attachmentFromFile(pathToFileURL(path));

    assert.equal(attachment.filename, "report.csv");
    assert.equal(attachment.contentBase64, Buffer.from("a,b\n1,2\n").toString("base64"));
  });
});

test("attachmentFromBuffer encodes in-memory bytes with only the filename by default", () => {
  const data = Buffer.from("generated bytes");
  const attachment = attachmentFromBuffer(data, { filename: "report.bin" });

  assert.deepEqual(attachment, {
    filename: "report.bin",
    contentBase64: data.toString("base64"),
  });
});

test("attachmentFromBuffer accepts a Uint8Array and all metadata options", () => {
  const data = new Uint8Array([1, 2, 3, 4]);
  const attachment = attachmentFromBuffer(data, {
    filename: "raw.dat",
    contentType: "application/octet-stream",
    inline: false,
    contentId: "raw",
  });

  assert.deepEqual(attachment, {
    filename: "raw.dat",
    contentBase64: Buffer.from(data).toString("base64"),
    contentType: "application/octet-stream",
    inline: false,
    contentId: "raw",
  });
});
